import Image from 'next/image'; import Link from 'next/link'; import {ArrowRight,Check,TrendingUp,Leaf,BriefcaseBusiness,Target} from 'lucide-react'; import {getServices,audiences} from '@/lib/data';
const imgs=['/images/coffee-farm.webp','/images/coffee-cup.webp','/images/coffee-processing.webp','/images/coffee-cherries.webp','/images/hero-coffee.webp'];
export default async function Home(){const svcs=await getServices();return <>
<section className="hero"><Image src="/images/hero-coffee.webp" alt="Coffee beans and agribusiness value chain" fill priority className="hero-img"/><div className="hero-overlay"/><div className="container hero-content"><span className="eyebrow light">FATHOM AGRIBUSINESSES LIMITED</span><h1>Turning Agribusiness Potential Into <em>Sustainable Growth.</em></h1><p>Practical, value-chain-driven solutions that help agribusinesses and SMEs plan better, build stronger businesses and unlock growth opportunities.</p><div className="actions"><Link className="btn" href="/services">Explore Our Services <ArrowRight size={18}/></Link><Link className="btn btn-ghost" href="/contact">Talk to an Advisor</Link></div></div><div className="trust"><div>Technical Knowledge</div><div>Value-Chain Expertise</div><div>Commercial Focus</div><div>Practical Solutions</div></div></section>
<section className="section"><div className="container split"><div><span className="eyebrow">WHO WE ARE</span><h2>Growing businesses.<br/>Building value.<br/><span>Creating markets.</span></h2><p className="lead">Fathom Agribusinesses Limited supports coffee enterprises and SMEs in building sustainable, market-oriented and investment-ready businesses.</p><p>We combine technical expertise, business strategy, market insight and value-chain know-how to turn ideas into structured, commercially viable enterprises.</p><Link className="text-link" href="/about">Discover Fathom <ArrowRight size={17}/></Link></div><div className="image-frame"><Image src="/images/coffee-farm.webp" alt="Coffee farming and value chain advisory" fill/></div></div></section>
<section className="section services-bg"><div className="container"><div className="section-head"><div><span className="eyebrow">OUR EXPERTISE</span><h2>Practical expertise across the <span>coffee value chain.</span></h2></div><p>From farm establishment to market positioning, our advisory work is designed around commercial reality.</p></div><div className="service-grid">{svcs.map((s:any,i:number)=><Link href={`/services/${s.slug}`} className="service-card" key={s.slug}><div className="service-image"><Image src={imgs[i%imgs.length]} alt={s.title} fill/></div><div className="service-body"><small>0{i+1}</small><h3>{s.title}</h3><p>{s.short_description}</p><span>Explore service <ArrowRight size={16}/></span></div></Link>)}</div></div></section>
<section className="section dark-section"><div className="container split reverse"><div className="image-frame tall"><Image src="/images/coffee-cherries.webp" alt="Ripe coffee cherries" fill/></div><div><span className="eyebrow light">WHO WE SERVE</span><h2>Built for the people <span>moving agriculture forward.</span></h2><div className="audience-list">{audiences.map(a=><div key={a}><Check size={17}/>{a}</div>)}</div><Link className="btn btn-light" href="/who-we-serve">See who we work with</Link></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">WHY FATHOM</span><h2>From potential to <span>performance.</span></h2></div><p>Clear thinking, practical support and commercial discipline across the agribusiness journey.</p></div><div className="value-grid"><article><Leaf/><h3>Technical Knowledge</h3><p>Grounded advice for the realities of coffee production and agribusiness.</p></article><article><BriefcaseBusiness/><h3>Business Strategy</h3><p>Structure ideas around sustainable, commercially viable models.</p></article><article><TrendingUp/><h3>Market Insight</h3><p>Build stronger market positioning and make better-informed decisions.</p></article><article><Target/><h3>Practical Execution</h3><p>Move beyond plans with support focused on real business outcomes.</p></article></div></div></section>
<section className="cta"><Image src="/images/coffee-processing.webp" alt="Coffee processing" fill/><div className="cta-overlay"/><div className="container cta-content"><span className="eyebrow light">START A CONVERSATION</span><h2>Ready to build a stronger agribusiness?</h2><p>Let’s turn your ideas, opportunities and investments into structured, sustainable and commercially viable enterprises.</p><Link className="btn btn-gold" href="/contact">Talk to an Advisor <ArrowRight size={18}/></Link></div></section>
</>}
